apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-robot
  namespace: wechat-robot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wechat-robot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: wechat-robot
    spec:
      containers:
        - image: wechatrobot-go:latest
          imagePullPolicy: IfNotPresent
          name: wechatrobot-go
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "1"
              memory: 1024Mi
            limits:
              cpu: "1"
              memory: 1024Mi
          ports:
            - name: http
              containerPort: 8080