apiVersion: v1
kind: Service
metadata:
  name: wechat-robot-service
  namespace: wechat-robot
spec:
  type: NodePort
  selector:
    app: wechat-robot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080